version: '3'

services:
  leaf-server:
    build: .
    ports:
      - '3333:3333'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: leaf
    ports:
      - '15432:5432'
    container_name: pg-leaf

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: leaf
    ports:
      - '37017:27017'
    container_name: mongodb-leaf
