version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: leaf
    ports:
      - '5432:5432'
    volumes:
      - ./data:/data/pg-db
    container_name: pg-leaf
    networks:
      - app_net

  mongo:
    image: mongo
    environment:
      MONGODB_USER: mongodb
      MONGODB_PASS: leaf
    ports:
      - '27017:27017'
    volumes:
      - ./data:/mongo-db
    container_name: mongodb-leaf
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
